### ISSUE TITLE
Bug on Airpair and typo

### ISSUE THREAD

**Issue by heitortsergent** [airpair/scalable-architecture-dr-con-docker-registrator-consul-consul-template-and-nginx#3]
@jkresner not related to the content of the post but one of the headers is not wrapping:

![image](https://cloud.githubusercontent.com/assets/446316/6630329/a7b6f850-c8e5-11e4-89eb-ac08160b574f.png)

And a small typo on the commit, it says "brach" instead of "branch":

![image](https://cloud.githubusercontent.com/assets/446316/6630333/bde9015e-c8e5-11e4-8447-ffb4376ded2d.png)

**Comment by jkresner** [comment]
Please do not use h1 tags in the body of your post. Not good for your SEO :)

On Thursday, March 12, 2015, Heitor Tashiro Sergent <
notifications@github.com> wrote:

> @jkresner https://github.com/jkresner not related to the content of the
> post but one of the headers is not wrapping:
> 
> [image: image]
> https://cloud.githubusercontent.com/assets/446316/6630329/a7b6f850-c8e5-11e4-89eb-ac08160b574f.png
> 
> And a small typo on the commit, it says "brach" instead of "branch":
> 
> [image: image]
> https://cloud.githubusercontent.com/assets/446316/6630333/bde9015e-c8e5-11e4-8447-ffb4376ded2d.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/airpair/scalable-architecture-dr-con-docker-registrator-consul-consul-template-and-nginx/issues/3
> .

## 

Jonathon Kresner
about.me http://about.me/jonathonkresner | hackerpreneurialism
http://hackerpreneurialism.com | @hackerpreneur
http://twitter.com/hackerpreneur

**Comment by grahamjenson** [comment]
I did not know that, good to know :)

**Comment by jkresner** [comment]
Yeah it was mentioned in the default markdown text, but the review process
is designed to catch these things anyway !

On Thursday, March 12, 2015, Graham Jenson notifications@github.com wrote:

> I did not know that, good to know :)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/airpair/scalable-architecture-dr-con-docker-registrator-consul-consul-template-and-nginx/issues/3#issuecomment-78694945
> .

## 

Jonathon Kresner
about.me http://about.me/jonathonkresner | hackerpreneurialism
http://hackerpreneurialism.com | @hackerpreneur
http://twitter.com/hackerpreneur

**Comment by grahamjenson** [comment]
I have merged pull request to change this, closing...

**Comment by jkresner** [comment]
@heitortsergent why aint sendgrid sponsoring our comp?

https://www.airpair.com/100k-writing-competition

**Comment by heitortsergent** [comment]
@jkresner good question, but I needed to update my profile, I'm not there anymore. Anyways, sounds like something they would like, did you reach out?

Let me know if I can help there. :dancer:

**Comment by jkresner** [comment]
@heitortsergent if you could make an intro the their Evangelist team that would be amazing. I knew the old team members only...

**Comment by heitortsergent** [comment]
@jkresner can you shoot me an email, heitortsergent@gmail.com? Happy to do it :D
